### ISSUE TITLE
Votes are deleted on all Statements whenever the "Configure Principles" statements are saved

### ISSUE THREAD

**Issue by evanhadfield** [collect-intel/osccai#37]
Triggering a save in the **Configure Principles** section of the flow replaces the Statements, causes all Votes on the "existing" statements to be deleted, and vote counts to be reset to 0.

Confirmed:

* clicking the pencil icon next to any Statement in this section, _even if no changes are made_, causes the "Save" to replace all of the Statements with brand new Statements (new `uid`, `createdAt`) with the same text
* no difference between whether the Statement is created by the poll creator in Configure principles or submitted by a Participant
* Votes on the replaced Statements are deleted

Desired fix:

* Really, these Statements should not be editable. The current interface allows for editing the text of all Statements which we don't want. We should really bar the editing of Statement text in any UI to preserve the integrity of Statement data (i.e. from being edited after Participants have already voted on past wording, or changing the language of what Participants have submitted). Creators can be allowed to _delete_ Statements for now, as a kind of rudimentary moderation and also for quickly sifting out undesired generated statements. So, partial fix is to **remove the ability to edit Statements in Configure Principles** (but keep Delete)
* Fix the "save" function to write over existing Statements, i.e. when new principles are added here manually or generated automatically.
* When users click "Add another principle", a new Statement box appears that they can type into. Once they click the check mark on that though, the Statement is created and saved to DB and becomes uneditable (except for deletion).
* Clicking "Generate some principles automatically" populates new Statements that are **not** editable. These are created + saved to DB immediately.

**Comment by padolsey** [comment]
Ok - [~fixed](https://github.com/collect-intel/osccai/commit/4fb76c50d306f4b8292ba11e26aaa4839dee5cbe) - statements now persist even when new ones are created manually _or_ generated. Agreed they should be non-editable; we can circle back to that as it's a rather simple UI-layer fix. Keeping this issue open for that purpose.

**Comment by evanhadfield** [comment]
Woo! thanks
